---
name: Bump package version

'on':
  pull_request:
    types: [labeled]

permissions:
  contents: write

jobs:
  bump-version:
    uses: drugscom/shared-workflows/.github/workflows/node-bump-version.yml@v1
