---
name: CD

'on':
  push:
    branches: [master]
    tags: [v*]
  workflow_dispatch:

concurrency:
  group: CD-new-release/${{ github.repo }}/${{ github.ref }}

permissions:
  contents: write

jobs:
  new-release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v1
      - name: Create new release
        uses: ./
        with:
          update-major-tag: true
