---
name: Build

'on':
  pull_request:
    paths: ['src/**']
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run build
      - name: Push changes
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          git add --all dist/
          git commit -m 'Update dist'
          git push
