---
name: Reset package version

'on':
  pull_request:
    types: [unlabeled]

permissions:
  contents: write

jobs:
  bump-version:
    uses: drugscom/shared-workflows/.github/workflows/node-reset-version.yml@v1
